version: '3.1'

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=minhaSenhaSegura
      - TZ=America/Sao_Paulo
    volumes:
      - ./.n8n:/home/node/.n8n
      - ./products.json:/home/node/products.json
